<a href="https://colab.research.google.com/github/iamviji/project/blob/master/PostMidTerm/TensorFlowBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the library 
import tensorflow as tf 
  
# Initializing the input tensor 
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float64) 
  
# Printing the input tensor 
print('Input: ', a) 
  
# Calculating result 
res = tf.math.reduce_mean(a, axis = 1) 
# Printing the result 
print('Result: ', res) 

# Calculating result 
res = tf.math.reduce_mean(a, axis = 0) 
# Printing the result 
print('Result: ', res) 


# Calculating result 
res = tf.math.reduce_mean(a) 
# Printing the result 
print('Result: ', res) 

Input:  Tensor("Const_3:0", shape=(2, 2), dtype=float64)
Result:  Tensor("Mean:0", shape=(2,), dtype=float64)
Result:  Tensor("Mean_1:0", shape=(2,), dtype=float64)
Result:  Tensor("Mean_2:0", shape=(), dtype=float64)


In [ ]:
# importing the library 
import tensorflow as tf 
  
# Initializing the input tensor 
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float64) 
  
# Printing the input tensor 
print('Input: ', a) 
  
# Calculating result 
res = tf.math.reduce_sum(a, axis = 1) 
# Printing the result 
print('Result: ', res) 
# Calculating result 
res = tf.math.reduce_sum(a, axis = 0) 
# Printing the result 
print('Result: ', res) 
# Calculating result 
res = tf.math.reduce_sum(a) 
# Printing the result 
print('Result: ', res) 

Input:  Tensor("Const_5:0", shape=(2, 2), dtype=float64)
Result:  Tensor("Sum_2:0", shape=(2,), dtype=float64)
Result:  Tensor("Sum_3:0", shape=(2,), dtype=float64)
Result:  Tensor("Sum_4:0", shape=(), dtype=float64)


In [ ]:
from keras import backend as K
import numpy
print(K.l2_normalize(a,axis=1))
print (1/numpy.sqrt(5))

tf.Tensor(
[[0.4472136  0.89442719]
 [0.6        0.8       ]], shape=(2, 2), dtype=float64)
0.4472135954999579


In [ ]:
# importing the library 
import tensorflow as tf 
  
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float64) 
print('Input: ', a) 

res = tf.square(a)
print('tf.square(a): ', res) 

res = tf.reduce_sum (res)
print('tf.reduce_sum(a): ', res) 

res = tf.sqrt (res)
print('tf.sqrt: ', res) 
#x  = tf.math.reciprocal (res)*tf.sqrt(2)
res1 = tf.expand_dims(x, 1)
print("res1", res1)

Input:  Tensor("Const_7:0", shape=(2, 2), dtype=float64)
tf.square(a):  Tensor("Square:0", shape=(2, 2), dtype=float64)
tf.reduce_sum(a):  Tensor("Sum_5:0", shape=(), dtype=float64)
tf.sqrt:  Tensor("Sqrt:0", shape=(), dtype=float64)


NameError: ignored

In [ ]:
 
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float64) 
print('Input: ', a)
print (tf.reduce_sum(tf.square(a), axis=1)) 
x = tf.sqrt(tf.reduce_sum(tf.square(a), axis=1))
print ("xxx")
print (x)
x = tf.reshape (x, (-1,1))
print ("xxx1")
print (x)
print ("xxx2")
print(a / x)


Input:  Tensor("Const_9:0", shape=(2, 2), dtype=float64)
Tensor("Sum_6:0", shape=(2,), dtype=float64)
xxx
Tensor("Sqrt_1:0", shape=(2,), dtype=float64)
xxx1
Tensor("Reshape:0", shape=(2, 1), dtype=float64)
xxx2
Tensor("truediv:0", shape=(2, 2), dtype=float64)


In [ ]:
a = tf.constant([[1, 0, 1], [0, 1, 0]], dtype = tf.float64) 
b = tf.constant([[0, 1, 1], [1, 0, 1]], dtype = tf.float64) 
print('Input: ', a-b)
print(tf.reduce_sum(tf.square(a-b), axis=1))
print (tf.reduce_mean(tf.sqrt(tf.reduce_sum(tf.square(a-b), axis=1)))) 
#x = tf.sqrt(tf.reduce_sum(tf.square(a), axis=1))
##print ("xxx")
#print(x)

Input:  Tensor("sub:0", shape=(2, 3), dtype=float64)
Tensor("Sum_8:0", shape=(2,), dtype=float64)
Tensor("Mean_3:0", shape=(), dtype=float64)


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior ()

binary_string = tf.constant([1, 0, 0])

result = tf.reduce_sum(
    tf.cast(tf.reverse(tensor=binary_string, axis=[0]), dtype=tf.int64)
    * 2 ** tf.range(tf.cast(tf.size(binary_string), dtype=tf.int64)))

with tf.Session():
    print(result.eval())

4


In [ ]:
binary_string = numpy.random.randint(2, size=(1,100))
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior ()



result = tf.reduce_sum(
    tf.cast(tf.reverse(tensor=binary_string, axis=[0]), dtype=tf.int64)
    * 2 ** tf.range(tf.cast(tf.size(binary_string), dtype=tf.int64)))

with tf.Session():
    print(result.eval())

5012952667607683667


In [134]:
def GetBerBler (input_message_binary1, input_message_binary2):
  diff = abs(input_message_binary1 - input_message_binary2)
  field_sum = np.sum (diff, axis=1)
  field_sum = np.reshape (field_sum, (-1,1))
  ber = np.sum(field_sum)/(input_message_binary1.shape[0]*input_message_binary1.shape[1])
  field_non_zero_count = np.count_nonzero(field_sum != 0, axis=1)
  bler = np.sum(field_non_zero_count)/field_non_zero_count.shape[0]
  return ber, bler
import numpy as np
x = np.array([[1,0,0],[1,1,1], [0,1,0]])
y = np.array([[1,1,0],[1,1,1], [0,0,1]])
print (GetBerBler(x,y))
inx = x
print (x)
x =np.sum (x, axis=1)
x = np.reshape (x, (-1,1))
print (x)
ber = np.sum(x)/(inx.shape[0]*inx.shape[1])
print ("ber:",ber)
y = np.count_nonzero(x != 0, axis=1)
bler = np.sum(y)/y.shape[0]
#y = np.reshape (y, (-1,1))
print (y)
print ("bler:",bler)




(0.3333333333333333, 0.6666666666666666)
[[1 0 0]
 [1 1 1]
 [0 1 0]]
[[1]
 [3]
 [1]]
ber: 0.5555555555555556
[1 1 1]
bler: 1.0


In [53]:
import numpy as np
xx = [0,1,2]
x = np.array([[1,0,0],[0,1,0], [0,0,1]])


In [85]:
import numpy
input_message_length = 4
training_input_message = numpy.random.randint(2**input_message_length, size=(1,5))
training_input_message_one_hot = numpy.zeros((training_input_message.size, 2**input_message_length))
print (numpy.arange(training_input_message.size))
training_input_message_one_hot[numpy.arange(training_input_message.size),training_input_message] = 1
print (training_input_message)
print (training_input_message_one_hot)

[0 1 2 3 4]
[[ 8  8 13  4  0]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:
y = [2,4]
[int(x) for x in list('{0:0b}'.format(102))]

TypeError: ignored

In [82]:

inx = [1,2,3,4,5]
xxx = [for i in range(len(inx)) for x in list('{0:0b}'.format(inx[i]))]
Dnum = 10
print (list('{0:0b}'.format(Dnum)))
print ('{0:0b}'.format(Dnum))
binnum = [int(i) for i in list('{0:0b}'.format(Dnum))]
print (binnum)

TypeError: ignored

In [116]:
def conv_to_binary_from_decimal (decimal,input_message_size, input_message_length):
  binary = numpy.random.randint(1, size=(input_message_size,input_message_length))
  for i in range (input_message_size):
    bin = [int(x) for x in list('{0:0b}'.format(decimal[0][i]))]
    #print(bin)
    for j in range (len(bin)):
      offset = input_message_length - len(bin)
      #print ("x",offset)
      binary [i][j+offset] = bin [j]
  return binary

print (training_input_message)
print (input_message)
conv_to_binary_from_decimal (training_input_message,5,4)


[[ 8  8 13  4  0]]
[[1 0 0 0]
 [1 0 0 0]
 [1 1 0 1]
 [0 1 0 0]
 [0 0 0 0]]
[1, 0, 0, 0]
x 0
x 0
x 0
x 0
[1, 0, 0, 0]
x 0
x 0
x 0
x 0
[1, 1, 0, 1]
x 0
x 0
x 0
x 0
[1, 0, 0]
x 1
x 1
x 1
[0]
x 3


array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 0]])