<a href="https://colab.research.google.com/github/iamviji/project/blob/master/PostMidTerm/TensorFlowBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the library 
import tensorflow as tf 
  
# Initializing the input tensor 
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float64) 
  
# Printing the input tensor 
print('Input: ', a) 
  
# Calculating result 
res = tf.math.reduce_mean(a, axis = 1) 
# Printing the result 
print('Result: ', res) 

# Calculating result 
res = tf.math.reduce_mean(a, axis = 0) 
# Printing the result 
print('Result: ', res) 


# Calculating result 
res = tf.math.reduce_mean(a) 
# Printing the result 
print('Result: ', res) 

Input:  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)
Result:  tf.Tensor([1.5 3.5], shape=(2,), dtype=float64)
Result:  tf.Tensor([2. 3.], shape=(2,), dtype=float64)
Result:  tf.Tensor(2.5, shape=(), dtype=float64)


In [ ]:
# importing the library 
import tensorflow as tf 
  
# Initializing the input tensor 
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float64) 
  
# Printing the input tensor 
print('Input: ', a) 
  
# Calculating result 
res = tf.math.reduce_sum(a, axis = 1) 
# Printing the result 
print('Result: ', res) 
# Calculating result 
res = tf.math.reduce_sum(a, axis = 0) 
# Printing the result 
print('Result: ', res) 
# Calculating result 
res = tf.math.reduce_sum(a) 
# Printing the result 
print('Result: ', res) 

Input:  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)
Result:  tf.Tensor([3. 7.], shape=(2,), dtype=float64)
Result:  tf.Tensor([4. 6.], shape=(2,), dtype=float64)
Result:  tf.Tensor(10.0, shape=(), dtype=float64)


In [ ]:
from keras import backend as K
import numpy
print(K.l2_normalize(a,axis=1))
print (1/numpy.sqrt(5))

tf.Tensor(
[[0.4472136  0.89442719]
 [0.6        0.8       ]], shape=(2, 2), dtype=float64)
0.4472135954999579


In [ ]:
# importing the library 
import tensorflow as tf 
  
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float64) 
print('Input: ', a) 

res = tf.square(a)
print('tf.square(a): ', res) 

res = tf.reduce_sum (res)
print('tf.reduce_sum(a): ', res) 

res = tf.sqrt (res)
print('tf.sqrt: ', res) 
#x  = tf.math.reciprocal (res)*tf.sqrt(2)
res1 = tf.expand_dims(x, 1)
print("res1", res1)

Input:  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)
tf.square(a):  tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float64)
tf.reduce_sum(a):  tf.Tensor(30.0, shape=(), dtype=float64)
tf.sqrt:  tf.Tensor(5.477225575051661, shape=(), dtype=float64)


NameError: ignored

In [ ]:
 
a = tf.constant([[1, 2], [3, 4]], dtype = tf.float64) 
print('Input: ', a)
print (tf.reduce_sum(tf.square(a), axis=1)) 
x = tf.sqrt(tf.reduce_sum(tf.square(a), axis=1))
print ("xxx")
print (x)
x = tf.reshape (x, (-1,1))
print ("xxx1")
print (x)
print ("xxx2")
print(a / x)


In [ ]:
a = tf.constant([[1, 0, 1], [0, 1, 0]], dtype = tf.float64) 
b = tf.constant([[0, 1, 1], [1, 0, 1]], dtype = tf.float64) 
print('Input: ', a-b)
print(tf.reduce_sum(tf.square(a-b), axis=1))
print (tf.reduce_mean(tf.sqrt(tf.reduce_sum(tf.square(a-b), axis=1)))) 
#x = tf.sqrt(tf.reduce_sum(tf.square(a), axis=1))
##print ("xxx")
#print(x)

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior ()

binary_string = tf.constant([1, 0, 0])

result = tf.reduce_sum(
    tf.cast(tf.reverse(tensor=binary_string, axis=[0]), dtype=tf.int64)
    * 2 ** tf.range(tf.cast(tf.size(binary_string), dtype=tf.int64)))

with tf.Session():
    print(result.eval())

4


In [ ]:
binary_string = numpy.random.randint(2, size=(1,100))
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior ()



result = tf.reduce_sum(
    tf.cast(tf.reverse(tensor=binary_string, axis=[0]), dtype=tf.int64)
    * 2 ** tf.range(tf.cast(tf.size(binary_string), dtype=tf.int64)))

with tf.Session():
    print(result.eval())

3858548623156079398
